[project]
name = "capstone-kevina"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "k3vina", email = "kevinajepkonga@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "ipykernel>=7.4.0",
    "jupyter>=1.1.1",
    "matplotlib>=3.11.2",
    "numpy>=2.5.3",
    "openpyxl>=3.1.5",
    "pandas>=3.0.6",
    "scipy>=1.18.1",
    "seaborn>=0.13.2",
    "statsmodels>=0.15.0",
    "streamlit>=1.65.0",
]

[project.scripts]
capstone-kevina = "capstone_kevina:main"

[build-system]
requires = ["uv_build>=0.12.22,<0.13.0"]
build-backend = "uv_build"
